import type { NextPage } from 'next'
import Head from 'next/head'
import { useCallback } from 'react'
import { DndProvider } from 'react-dnd'
import { HTML5Backend } from 'react-dnd-html5-backend'
import styles from '../styles/Home.module.css'
import { ResumePaper } from './components/paper'

const MyResume: NextPage = () => {

    return (
        <div className={styles.container}>
            <Head>
                <title>MyResume</title>
                {/* <meta name="description" content="Generated by create next app" /> */}
            </Head>

            <main>
                <DndProvider backend={HTML5Backend}>
                    <ResumePaper />
                </DndProvider>
            </main>

            <footer className={styles.footer}>

            </footer>
        </div>
    )
}

export default MyResume
